---
name: 'Sensu Catalog API Generator'
description: 'Generate Sensu Catalog API from a Catalog repository'
author: 'sensu'
inputs:
  catalog-api-version:
    description: 'The version of the API tool to use'
    type: string
    default: '0.1.0-alpha.11'
  snapshot:
    description: 'Enables generation of the API from a snapshot'
    type: boolean
    default: false
  temp-dir:
    description: 'The path to a temp directory to store the generated API files'
    type: string
    default: './tmp'
outputs:
  release-dir:
    description: 'The path of the generated release directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.catalog-api-version }}
    - ${{ inputs.temp-dir }}
    - ${{ inputs.snapshot }}
branding:
  icon: 'globe'
  color: 'green'
